# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/frenet_main_window.ui'
#
# Created: Wed Oct 24 23:29:10 2018
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 795)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dynamics_widget = DynamicsWidget(self.centralwidget)
        self.dynamics_widget.setObjectName("dynamics_widget")
        self.verticalLayout_3.addWidget(self.dynamics_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1066, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dw_dynamics = QtWidgets.QDockWidget(MainWindow)
        self.dw_dynamics.setObjectName("dw_dynamics")
        self.dwc_dynamics = QtWidgets.QWidget()
        self.dwc_dynamics.setObjectName("dwc_dynamics")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dwc_dynamics)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gb_Start = QtWidgets.QGroupBox(self.dwc_dynamics)
        self.gb_Start.setObjectName("gb_Start")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gb_Start)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_s0 = QtWidgets.QLabel(self.gb_Start)
        self.lbl_s0.setObjectName("lbl_s0")
        self.gridLayout_2.addWidget(self.lbl_s0, 0, 0, 1, 1)
        self.dsb_s0 = QtWidgets.QDoubleSpinBox(self.gb_Start)
        self.dsb_s0.setObjectName("dsb_s0")
        self.gridLayout_2.addWidget(self.dsb_s0, 0, 1, 1, 1)
        self.lbl_v0 = QtWidgets.QLabel(self.gb_Start)
        self.lbl_v0.setObjectName("lbl_v0")
        self.gridLayout_2.addWidget(self.lbl_v0, 1, 0, 1, 1)
        self.dsb_v0 = QtWidgets.QDoubleSpinBox(self.gb_Start)
        self.dsb_v0.setProperty("value", 10.0)
        self.dsb_v0.setObjectName("dsb_v0")
        self.gridLayout_2.addWidget(self.dsb_v0, 1, 1, 1, 1)
        self.lbl_a0 = QtWidgets.QLabel(self.gb_Start)
        self.lbl_a0.setObjectName("lbl_a0")
        self.gridLayout_2.addWidget(self.lbl_a0, 2, 0, 1, 1)
        self.dsb_a0 = QtWidgets.QDoubleSpinBox(self.gb_Start)
        self.dsb_a0.setObjectName("dsb_a0")
        self.gridLayout_2.addWidget(self.dsb_a0, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.gb_Start)
        self.gb_End = QtWidgets.QGroupBox(self.dwc_dynamics)
        self.gb_End.setObjectName("gb_End")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gb_End)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_stau = QtWidgets.QLabel(self.gb_End)
        self.lbl_stau.setObjectName("lbl_stau")
        self.gridLayout_3.addWidget(self.lbl_stau, 0, 0, 1, 1)
        self.dsb_stau = QtWidgets.QDoubleSpinBox(self.gb_End)
        self.dsb_stau.setProperty("value", 50.0)
        self.dsb_stau.setObjectName("dsb_stau")
        self.gridLayout_3.addWidget(self.dsb_stau, 0, 1, 1, 1)
        self.lbl_vtau = QtWidgets.QLabel(self.gb_End)
        self.lbl_vtau.setObjectName("lbl_vtau")
        self.gridLayout_3.addWidget(self.lbl_vtau, 1, 0, 1, 1)
        self.dsb_vtau = QtWidgets.QDoubleSpinBox(self.gb_End)
        self.dsb_vtau.setProperty("value", 10.0)
        self.dsb_vtau.setObjectName("dsb_vtau")
        self.gridLayout_3.addWidget(self.dsb_vtau, 1, 1, 1, 1)
        self.lbl_atau = QtWidgets.QLabel(self.gb_End)
        self.lbl_atau.setObjectName("lbl_atau")
        self.gridLayout_3.addWidget(self.lbl_atau, 2, 0, 1, 1)
        self.dsb_atau = QtWidgets.QDoubleSpinBox(self.gb_End)
        self.dsb_atau.setObjectName("dsb_atau")
        self.gridLayout_3.addWidget(self.dsb_atau, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.gb_End)
        self.dw_dynamics.setWidget(self.dwc_dynamics)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dw_dynamics)
        self.dw_settings = QtWidgets.QDockWidget(MainWindow)
        self.dw_settings.setObjectName("dw_settings")
        self.dwc_settings = QtWidgets.QWidget()
        self.dwc_settings.setObjectName("dwc_settings")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dwc_settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gb_time_settings = QtWidgets.QGroupBox(self.dwc_settings)
        self.gb_time_settings.setObjectName("gb_time_settings")
        self.gridLayout = QtWidgets.QGridLayout(self.gb_time_settings)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_tau = QtWidgets.QLabel(self.gb_time_settings)
        self.lbl_tau.setObjectName("lbl_tau")
        self.gridLayout.addWidget(self.lbl_tau, 0, 0, 1, 1)
        self.dsb_tau = QtWidgets.QDoubleSpinBox(self.gb_time_settings)
        self.dsb_tau.setProperty("value", 5.0)
        self.dsb_tau.setObjectName("dsb_tau")
        self.gridLayout.addWidget(self.dsb_tau, 0, 1, 1, 1)
        self.lbl_s0_2 = QtWidgets.QLabel(self.gb_time_settings)
        self.lbl_s0_2.setObjectName("lbl_s0_2")
        self.gridLayout.addWidget(self.lbl_s0_2, 1, 0, 1, 1)
        self.dsb_lookahead_time = QtWidgets.QDoubleSpinBox(self.gb_time_settings)
        self.dsb_lookahead_time.setObjectName("dsb_lookahead_time")
        self.gridLayout.addWidget(self.dsb_lookahead_time, 1, 1, 1, 1)
        self.lbl_s0_3 = QtWidgets.QLabel(self.gb_time_settings)
        self.lbl_s0_3.setObjectName("lbl_s0_3")
        self.gridLayout.addWidget(self.lbl_s0_3, 2, 0, 1, 1)
        self.dsb_sampling_rate = QtWidgets.QDoubleSpinBox(self.gb_time_settings)
        self.dsb_sampling_rate.setProperty("value", 0.01)
        self.dsb_sampling_rate.setObjectName("dsb_sampling_rate")
        self.gridLayout.addWidget(self.dsb_sampling_rate, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.gb_time_settings)
        self.dw_settings.setWidget(self.dwc_settings)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dw_settings)
        self.dw_polynomials = QtWidgets.QDockWidget(MainWindow)
        self.dw_polynomials.setObjectName("dw_polynomials")
        self.dwc_polynomials = QtWidgets.QWidget()
        self.dwc_polynomials.setObjectName("dwc_polynomials")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dwc_polynomials)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gb_set_polynomials = QtWidgets.QGroupBox(self.dwc_polynomials)
        self.gb_set_polynomials.setObjectName("gb_set_polynomials")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gb_set_polynomials)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pb_set_long = QtWidgets.QPushButton(self.gb_set_polynomials)
        self.pb_set_long.setObjectName("pb_set_long")
        self.gridLayout_4.addWidget(self.pb_set_long, 0, 0, 1, 1)
        self.pb_set_lat = QtWidgets.QPushButton(self.gb_set_polynomials)
        self.pb_set_lat.setObjectName("pb_set_lat")
        self.gridLayout_4.addWidget(self.pb_set_lat, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.gb_set_polynomials)
        self.dw_polynomials.setWidget(self.dwc_polynomials)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dw_polynomials)
        self.dw_path = QtWidgets.QDockWidget(MainWindow)
        self.dw_path.setObjectName("dw_path")
        self.dwc_path = QtWidgets.QWidget()
        self.dwc_path.setObjectName("dwc_path")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dwc_path)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.path_widget = PathWidget(self.dwc_path)
        self.path_widget.setObjectName("path_widget")
        self.verticalLayout_2.addWidget(self.path_widget)
        self.dw_path.setWidget(self.dwc_path)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dw_path)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.dw_dynamics.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Dynamics", None, -1))
        self.gb_Start.setTitle(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.lbl_s0.setText(QtWidgets.QApplication.translate("MainWindow", "s_0", None, -1))
        self.lbl_v0.setText(QtWidgets.QApplication.translate("MainWindow", "v_0", None, -1))
        self.lbl_a0.setText(QtWidgets.QApplication.translate("MainWindow", "a_0", None, -1))
        self.gb_End.setTitle(QtWidgets.QApplication.translate("MainWindow", "End", None, -1))
        self.lbl_stau.setText(QtWidgets.QApplication.translate("MainWindow", "s_tau", None, -1))
        self.lbl_vtau.setText(QtWidgets.QApplication.translate("MainWindow", "v_tau", None, -1))
        self.lbl_atau.setText(QtWidgets.QApplication.translate("MainWindow", "a_tau", None, -1))
        self.dw_settings.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.gb_time_settings.setTitle(QtWidgets.QApplication.translate("MainWindow", "Time Settings", None, -1))
        self.lbl_tau.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Reaction time", None, -1))
        self.lbl_tau.setText(QtWidgets.QApplication.translate("MainWindow", "tau", None, -1))
        self.lbl_s0_2.setText(QtWidgets.QApplication.translate("MainWindow", "Lookahead", None, -1))
        self.lbl_s0_3.setText(QtWidgets.QApplication.translate("MainWindow", "Sampling rate", None, -1))
        self.gb_set_polynomials.setTitle(QtWidgets.QApplication.translate("MainWindow", "Set Polynomials", None, -1))
        self.pb_set_long.setText(QtWidgets.QApplication.translate("MainWindow", "Set Longitudinal", None, -1))
        self.pb_set_lat.setText(QtWidgets.QApplication.translate("MainWindow", "Set Lateral", None, -1))

from widgets.path_widget import PathWidget
from widgets.dynamics_widget import DynamicsWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

